### ISSUE TITLE
Can´t run dev enviroment

### ISSUE THREAD

**Issue by grochadc** [niamu/hawkthorne-return#1]
I followed the instructions: `lein run`

But I get an error:
```Clojure
Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/util.cljc:1:1)
```
Running on macOs Mojave

**Comment by niamu** [comment]
Not sure what would cause that error. What version of Java are you running? I'm on OpenJDK version 1.8.0_192 with Leiningen version 2.8.1 and can't reproduce that error.

For what it's worth you may find the "phaser" branch more interesting than the master branch. I had more working in the phaser branch, but ultimately lost interest after a while because I couldn't come up with game ideas that would work work in a multiplayer setting that would be achievable by myself using the existing assets.

If you've got some game ideas, I'm interested.

**Comment by niamu** [comment]
Spent some more time experimenting with newer Java versions and was able to reproduce this error and resolve it.
